# Generated by Django 4.1.5 on 2023-09-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bulletpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletpoint',
            old_name='text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
