# Generated by Django 4.1.5 on 2023-10-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0004_alter_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomplishments',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='bulletpoint',
            old_name='user_profile',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='user_profile',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='user_profile',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
