# Generated by Django 4.1.5 on 2023-09-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bulletpoint_description_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='job_duties',
        ),
        migrations.AddField(
            model_name='experience',
            name='job_description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_description_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_description_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_description_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
