# Generated by Django 4.1.5 on 2023-09-29 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_experience_job_duties_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='job_description_1',
            new_name='description_1',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_description_2',
            new_name='description_2',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_description_3',
            new_name='description_3',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_description_4',
            new_name='description_4',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_description_5',
            new_name='description_5',
        ),
    ]
