# Generated by Django 4.1.5 on 2023-10-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_user_accomplishments_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user',
            new_name='username',
        ),
    ]
