# Generated by Django 4.1.5 on 2023-09-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_job_description_1_experience_description_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description_1',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description_3',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description_4',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description_5',
        ),
        migrations.AddField(
            model_name='experience',
            name='job_descriptions',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='core.bulletpoint'),
        ),
    ]
