# Generated by Django 4.1.5 on 2023-10-13 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_user_education_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomplishments',
            old_name='username',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='bulletpoint',
            old_name='username',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='username',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='username',
            new_name='user_profile',
        ),
        migrations.AddField(
            model_name='experience',
            name='description_6',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=500)]),
        ),
    ]
