# Generated by Django 4.1.5 on 2023-10-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_username_accomplishments_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomplishments',
            old_name='user_profile',
            new_name='user',
        ),
    ]
