# Generated by Django 4.1.5 on 2023-09-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_experience_description_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='job_descriptions',
        ),
        migrations.AddField(
            model_name='experience',
            name='description_1',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_2',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_3',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_4',
            field=models.TextField(default='Default Description'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_5',
            field=models.TextField(default='Default Description'),
        ),
    ]
