# Generated by Django 4.1.5 on 2023-09-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_experience_job_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
