# Generated by Django 4.1.5 on 2023-09-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_experience_description_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='summary_statement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
