# Generated by Django 4.1.5 on 2023-10-03 00:07

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description_1',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=500)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_2',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=500)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_3',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=500)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_4',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=500)]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description_5',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=500)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='images/default.jpg', upload_to=core.models.resize_profile_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
