# Generated by Django 4.1.5 on 2023-10-03 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_accomplishment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accomplishment_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='accomplishments',
        ),
        migrations.CreateModel(
            name='Accomplishments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accomplishments', models.CharField(max_length=255)),
                ('accomplishment_image', models.ImageField(blank=True, null=True, upload_to='certs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
    ]
