# Generated by Django 4.1.5 on 2023-10-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_userprofile_accomplishment_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletpoint',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
